name: Сборка проекта

on:
  pull_request:
    branches:
      - '*'


jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Сборка проекта
        run: |
          echo "началос сборки"
          touch abc1.js
          git config --global user.name "lwod" ; git config --global user.email "lwodcurrentmail@gmail.com"
          git add .
          git commit -m "abc.js"
          git push https://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@github.com/lwod/gitbranches.git test_branch2
          git status
          echo "конец сборки"
      - name: Тест покрытия проекта
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
